In [ ]:
#Yesterday's Knowledge
import numpy as np


a = np.array([2, 4, 6, 8, 10])

print(a.shape)
print(np.mean(a))
print(np.std(a))
normalized = (a - np.mean(a)) / np.std(a)
print(np.mean(normalized))
print(np.std(normalized))


(5,)
6.0
2.8284271247461903
0.0
0.9999999999999999


In [ ]:
import numpy as np

a = np.arange(12)
print(a)
print(a.reshape(3, 4))
print(a.reshape(2, 6))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
import numpy as np

scores = np.array([45, 78, 23, 91, 60, 55, 88, 34, 72, 95])

print(scores[scores > 60])
print(scores[scores < 50])
print(scores[scores == 95])
print(scores > 60)

[78 91 88 72 95]
[45 23 34]
[95]
[False  True False  True False False  True False  True  True]


In [8]:
import numpy as np

#fake house dataset
sizes = np.array([600, 800, 1000, 1200, 1500])
prices = np.array([300, 400, 500, 600, 750])

#model parameters
w = 0.5
b = 0

#predict
predicted = w * sizes + b

# coumpute loss
mse = np.mean((predicted - prices) ** 2)

print(f"Predicted: {predicted}")
print(f"Actual: {prices}")
print(f"MSE Loss: {mse:.2f}")

Predicted: [300. 400. 500. 600. 750.]
Actual: [300 400 500 600 750]
MSE Loss: 0.00
