In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [ ]:
import numpy as np

print(np.zeros((3, 4)))
print(np.ones((2,3)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[0])
print(a[1][2])
print(a[:, 1])
print(a[0:2, 1:3])

[1 2 3]
6
[2 5 8]
[[2 3]
 [5 6]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a+b)
print(a*b)
print(a ** 2)
print(np.dot(a, b))
print(np.mean(a))
print(np.std(a))

normalized = (a - np.mean(a)) / np.std(a) #Important
print(normalized)
print(np.mean(normalized))
print(np.std(normalized))

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
550
3.0
1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.0
0.9999999999999999
